services:
  frontend:
    image: frontend
    pull_policy: build
    build:
      context: frontend
    ports:
      - "8000:8000"
    environment:
      - BACKEND_URL=http://backend:8001
    volumes:
      - ../week_1/data/3_gold/jobs.db:/data/jobs.db:ro
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    image: backend
    pull_policy: build
    build:
      context: backend
    environment:
      - GOOGLE_API_KEY=/run/secrets/google_api_key
      - DB_PATH=/data/jobs.db
    secrets:
      - google_api_key
    volumes:
      - ../week_1/data/3_gold/jobs.db:/data/jobs.db:ro
    networks:
      - app-network

secrets:
  google_api_key:
    file: ./secrets/google_api_key.txt

networks:
  app-network:
    driver: bridge